server "lig.symmachus.org" {
	log style combined
        directory { auto index }
        listen on $listen_addr port 80
        root "/vhosts/lig.symmachus.org/htdocs"

        location "/cgi-bin/audit-status.cgi" {
            fastcgi
            root "/vhosts/lig.symmachus.org"
        }

        location "/cgi-bin/fulltext-status.cgi" {
            fastcgi
            root "/vhosts/lig.symmachus.org"
        }

        location "/cgi-bin/audit*.cgi" {
            fastcgi
            root "/vhosts/lig.symmachus.org"
            authenticate "LIG Human Audit" with "/vhosts/lig.symmachus.org/etc/htpasswd"
        }

        location "/cgi-bin/fulltext*.cgi" {
            fastcgi
            root "/vhosts/lig.symmachus.org"
            authenticate "LIG Human Audit" with "/vhosts/lig.symmachus.org/etc/htpasswd"
        }

        location "/db/*" {
            block
        }
}
